FROM golang:1.22.5 as builder

WORKDIR /app

COPY ./go.* ./

RUN go install github.com/swaggo/swag/cmd/swag@latest \
    && go get -u github.com/swaggo/gin-swagger \
    && go get -u github.com/swaggo/swag \
    && go get -u github.com/swaggo/files

RUN go mod download

COPY . .

RUN swag init -g ./cmd/worker/main.go
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v -o /app/worker_polyglot_sentences ./cmd/worker/main.go

FROM alpine:3.15

WORKDIR /app

COPY --from=builder /app/worker_polyglot_sentences /app/
COPY --from=builder /app/.env.docker /app/.env
COPY --from=builder /app/pkg/translation/lang /app/pkg/translation/lang
COPY --from=builder /app/internal/core/views /app/internal/core/views

CMD ["/app/worker_polyglot_sentences"]
