apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: polyglot-sentences
  labels:
    app: auth
    type: back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      name: auth-deployment
      namespace: polyglot-sentences
      labels:
        name: polyglot-sentences-deployment
        app: auth
        type: back-end
    spec:
      containers:
        - name: auth-container
          image: mohsenabedy1991/auth_polyglot_sentences:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 2525
              path: /en/v1/health/check
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 2525
              path: /en/v1/health/check
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 2525
          env:
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: polyglot-sentences-secret
                  key: JWT_ACCESS_TOKEN_SECRET
            - name: PROFILE_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: polyglot-sentences-env-config
                  key: PROFILE_DEBUG
            - name: PROFILE_PORT
              valueFrom:
                configMapKeyRef:
                  name: polyglot-sentences-env-config
                  key: PROFILE_PORT
            - name: USER_MANAGEMENT_GRPC_URL
              value: user-management-grpc-service.polyglot-sentences.svc.cluster.local
          volumeMounts:
            - name: polyglot-sentences-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: polyglot-sentences-volume
          configMap:
            name: polyglot-sentences-file-config