apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: polyglot-sentences
  labels:
    app: auth
    type: back-end
spec:
  type: ClusterIP
  selector:
    app: auth
    type: back-end
  ports:
    - protocol: TCP
      targetPort: 2525
      port: 80