apiVersion: v1
kind: Service
metadata:
  name: user-management-grpc-service
  namespace: polyglot-sentences
  labels:
    app: user-management
    type: back-end
spec:
  type: ClusterIP
  selector:
    name: polyglot-sentences-deployment
  ports:
    - protocol: TCP
      targetPort: 2536
      port: 2536