apiVersion: v1
kind: Service
metadata:
  name: user-management-http-service
  namespace: polyglot-sentences
  labels:
    app: user-management
    type: back-end
spec:
  type: ClusterIP
  selector:
    app: user-management
    type: back-end
  ports:
    - protocol: TCP
      targetPort: 2535
      port: 80