FROM golang:1.22.5 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go install github.com/swaggo/swag/cmd/swag@latest \
    && go get -u github.com/swaggo/gin-swagger \
    && go get -u github.com/swaggo/swag \
    && go get -u github.com/swaggo/files

RUN go mod download

COPY .. .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v -o /app/notification_polyglot_sentences ./cmd/notificationserver/main.go

FROM alpine:3.15

WORKDIR /app

COPY --from=builder /app/notification_polyglot_sentences /app/
COPY --from=builder /app/.env.docker /app/.env
COPY --from=builder /app/pkg/translation/lang /app/pkg/translation/lang
COPY --from=builder /app/internal/core/views /app/internal/core/views

CMD ["/app/notification_polyglot_sentences"]
