FROM alpine:3.15

WORKDIR /app

COPY --from=builder notification_polyglot_sentences /app/
COPY --from=builder pkg/translation/lang /app/pkg/translation/lang
COPY --from=builder internal/core/views /app/internal/core/views

CMD ["/app/notification_polyglot_sentences"]
