FROM jenkins/jenkins:latest

USER root

# Install Docker
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce-cli

# Create Docker group if it doesn't exist and add Jenkins user to it
RUN if ! getent group docker > /dev/null; then groupadd docker; fi && \
    usermod -aG docker jenkins

USER jenkins
