apiVersion: v1
kind: ConfigMap
metadata:
  name: polyglot-sentences-file-config
  namespace: polyglot-sentences
data:
  .env: |
    APP_NAME=polyglot-sentences
    APP_ENV=development
    APP_DEBUG=true
    APP_TIMEZONE=UTC
    APP_RESET_PASSWORD_URL=https://polyglot-sentences.com/reset-password?token=
    APP_VERIFICATION_URL=https://polyglot-sentences.com/verify-email?token=
    APP_SUPPORT_EMAIL=support@polyglot-sentences.com
    
    APP_LOCALE=en
    APP_PATH_LOCALE=pkg/translation
    
    APP_GRACEFULLY_SHUTDOWN=1
    
    AUTH_NAME=auth-polyglot-sentences
    AUTH_VERSION=1.0.0
    AUTH_URL=
    AUTH_PORT=2525
    AUTH_DEBUG=true
    
    USER_MANAGEMENT_NAME=user-management-polyglot-sentences
    USER_MANAGEMENT_VERSION=1.0.0
    USER_MANAGEMENT_HTTP_URL=
    USER_MANAGEMENT_HTTP_PORT=2535
    USER_MANAGEMENT_GRPC_URL=
    USER_MANAGEMENT_GRPC_PORT=2536
    USER_MANAGEMENT_DEBUG=true
    
    NOTIFICATION_NAME=notification
    NOTIFICATION_VERSION=1.0.0
    NOTIFICATION_URL=
    NOTIFICATION_PORT=
    NOTIFICATION_DEBUG=true
    
    LOG_FILE_PATH=./logs/logs-
    LOG_LEVEL=debug
    LOG_MAX_SIZE=1
    LOG_MAX_AGE=5
    LOG_MAX_BACKUPS=10
    
    SWAGGER_HOST=localhost:1515
    SWAGGER_SCHEMES=http
    SWAGGER_INFO_TITLE=PolyglotSentences
    SWAGGER_INFO_DESCRIPTION="polyglot-sentences API"
    SWAGGER_INFO_VERSION=1.0.0
    SWAGGER_ENABLE=true
    SWAGGER_USERNAME=admin
    SWAGGER_PASSWORD=admin
    
    DB_CONNECTION=postgres
    DB_HOST=192.168.1.104
    DB_PORT=5425
    DB_NAME=polyglot_sentences
    DB_USERNAME=polyglot_sentences
    DB_PASSWORD=polyglot_sentences
    DB_POSTGRES_SSL_MODE=disable
    DB_POSTGRES_MAX_OPEN_CONNECTIONS=100
    DB_POSTGRES_MAX_IDLE_CONNECTIONS=15
    DB_POSTGRES_MAX_LIFETIME=5
    DB_POSTGRES_TIMEZONE=UTC
    
    REDIS_HOST=192.168.1.104
    REDIS_PORT=6325
    REDIS_PASSWORD=
    REDIS_DB=0
    REDIS_PREFIX=polyglot_sentences
    REDIS_DIAL_TIMEOUT=5
    REDIS_READ_TIMEOUT=5
    REDIS_WRITE_TIMEOUT=5
    REDIS_POOL_SIZE=10
    REDIS_POOL_TIMEOUT=15
    REDIS_IDLE_TIMEOUT=5
    REDIS_IDLE_CHECK_FREQUENCY=600
    
    JWT_ACCESS_TOKEN_EXPIRE_DAY=7
    
    PASSWORD_BCRYPT_COST=11
    
    OAUTH_GOOGLE_CLIENT_ID=
    OAUTH_GOOGLE_CLIENT_SECRET=
    OAUTH_GOOGLE_CALLBACK_URL=http://localhost
    
    OTP_EXPIRE_SECOND=180
    FORGET_PASSWORD_EXPIRE_SECOND=86400
    OTP_DIGITS=4
    
    RABBITMQ_URL=amqp://guest:guest@192.168.1.104:5672/
    
    SEND_GRID_NAME="Polyglot Sentences"
    SEND_GRID_ADDRESS=support@polyglot-sentences.com
    
    MINIO_ENDPOINT=192.168.1.104
    MINIO_PORT=9000
    MINIO_ID=polyglot_sentences
    MINIO_SECRET=polyglot_sentences
    MINIO_BUCKET_NAME=images
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: polyglot-sentences-env-config
  namespace: polyglot-sentences
data:
  PROFILE_DEBUG: "true"
  PROFILE_PORT: "2520"