apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-service
  namespace: jenkins
  labels:
    app: jenkins-master
    version: latest
    group: jenkins
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: jnlp
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins-master
    version: latest
    group: jenkins