-- Table: users
CREATE TABLE IF NOT EXISTS users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_users PRIMARY KEY,
    uuid        uuid                     DEFAULT gen_random_uuid() UNIQUE,
    language_id INTEGER
        CONSTRAINT fk_users_language_id REFERENCES languages,
    first_name  VARCHAR(128),
    last_name   VARCHAR(128),
    email       VARCHAR(128) UNIQUE,
    password    VARCHAR(255),
    google_id   VARCHAR(255) UNIQUE,
    facebook_id VARCHAR(255) UNIQUE,
    apple_id    VARCHAR(255) UNIQUE,
    last_login  TIMESTAMP WITH TIME ZONE,
    avatar      TEXT,
    status      user_status_type         DEFAULT 'UNVERIFIED'::user_status_type,
    created_by  INTEGER
        CONSTRAINT fk_users_created_by REFERENCES users,
    updated_by  INTEGER
        CONSTRAINT fk_users_updated_by REFERENCES users,
    deleted_by  INTEGER
        CONSTRAINT fk_users_deleted_by REFERENCES users,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT now(),
    deleted_at  TIMESTAMP WITH TIME ZONE
);

-- Index: idx_users_email
CREATE INDEX IF NOT EXISTS idx_users_email
    ON users (email);