-- Table: access_controls
CREATE TABLE IF NOT EXISTS access_controls
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_access_controls PRIMARY KEY,

    user_id       INTEGER NOT NULL,
    role_id       INTEGER,
    permission_id INTEGER,

    created_by    INTEGER
        CONSTRAINT fk_access_controls_created_by REFERENCES users,
    updated_by    INTEGER
        CONSTRAINT fk_access_controls_updated_by REFERENCES users,
    deleted_by    INTEGER
        CONSTRAINT fk_access_controls_deleted_by REFERENCES users,

    created_at    TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT now(),
    deleted_at    TIMESTAMP WITH TIME ZONE,

    UNIQUE (user_id, role_id, deleted_at),
    UNIQUE (user_id, permission_id, deleted_at),

    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (role_id) REFERENCES roles (id),
    FOREIGN KEY (permission_id) REFERENCES permissions (id)
);