-- Table: roles
CREATE TABLE IF NOT EXISTS roles
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_roles PRIMARY KEY,
    uuid        uuid                     DEFAULT gen_random_uuid() UNIQUE,
    title       VARCHAR(64) NOT NULL UNIQUE,
    key         VARCHAR(64) NOT NULL UNIQUE,
    description TEXT,
    created_by  INTEGER
        CONSTRAINT fk_roles_created_by REFERENCES users,
    updated_by  INTEGER
        CONSTRAINT fk_roles_updated_by REFERENCES users,
    deleted_by  INTEGER
        CONSTRAINT fk_roles_deleted_by REFERENCES users,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT now(),
    deleted_at  TIMESTAMP WITH TIME ZONE
);