-- Table: user_recovery_codes
CREATE TABLE IF NOT EXISTS user_recovery_codes
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_user_recovery_codes PRIMARY KEY,

    user_id    INTEGER      NOT NULL,
    code       VARCHAR(255) NOT NULL,
    used       BOOLEAN                  DEFAULT FALSE,

    created_by INTEGER
        CONSTRAINT fk_user_recovery_codes_created_by REFERENCES users,
    updated_by INTEGER
        CONSTRAINT fk_user_recovery_codes_updated_by REFERENCES users,
    deleted_by INTEGER
        CONSTRAINT fk_user_recovery_codes_deleted_by REFERENCES users,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    deleted_at TIMESTAMP WITH TIME ZONE,

    UNIQUE (user_id, code, deleted_at),

    FOREIGN KEY (user_id) REFERENCES users (id)
);