DELETE
FROM role_permissions
WHERE (role_id = 1 AND permission_id = 1)
   OR (role_id = 1 AND permission_id = 2)
   OR (role_id = 1 AND permission_id = 3)
   OR (role_id = 1 AND permission_id = 4)
   OR (role_id = 1 AND permission_id = 5)
   OR (role_id = 1 AND permission_id = 6)
   OR (role_id = 1 AND permission_id = 7)
   OR (role_id = 1 AND permission_id = 8)
   OR (role_id = 1 AND permission_id = 9)
   OR (role_id = 1 AND permission_id = 10)
   OR (role_id = 1 AND permission_id = 11)
   OR (role_id = 1 AND permission_id = 12)
   OR (role_id = 1 AND permission_id = 13)
   OR (role_id = 1 AND permission_id = 14)
   OR (role_id = 1 AND permission_id = 15)
   OR (role_id = 1 AND permission_id = 16)
   OR (role_id = 1 AND permission_id = 17)
   OR (role_id = 1 AND permission_id = 18)
   OR (role_id = 1 AND permission_id = 19)
   OR (role_id = 1 AND permission_id = 20)
   OR (role_id = 2 AND permission_id = 1)
   OR (role_id = 2 AND permission_id = 2)
   OR (role_id = 2 AND permission_id = 3)
   OR (role_id = 2 AND permission_id = 4)
   OR (role_id = 7 AND permission_id = 2);