-- Table: permissions
CREATE TABLE IF NOT EXISTS permissions
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_permissions PRIMARY KEY,
    uuid        uuid                     DEFAULT gen_random_uuid() UNIQUE,
    title       VARCHAR(64) NOT NULL UNIQUE,
    key         VARCHAR(64) NOT NULL UNIQUE,
    "group"     VARCHAR(64),
    description TEXT,
    created_by  INTEGER
        CONSTRAINT fk_permissions_created_by REFERENCES users,
    updated_by  INTEGER
        CONSTRAINT fk_permissions_updated_by REFERENCES users,
    deleted_by  INTEGER
        CONSTRAINT fk_permissions_deleted_by REFERENCES users,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT now(),
    deleted_at  TIMESTAMP WITH TIME ZONE
);